### PR TITLE
merge commits

### PR DESCRIPTION
**Pull request by ArsalanArdeshiri**
Final and Merged Commits for Hermes Team

### CODE REVIEW

**Comment by ArsalanArdeshiri** [comment]
I just squashed different commits into one and ask for final checkout

**Comment by ArsalanArdeshiri** [comment]
sorry for previous time, i was using graphic user interface and that made those bad commits

**Comment by ltratt** [comment]
No problem. Can you please change the title of the commit to something other than "merge commits" and then we should be OK.

**Comment by ArsalanArdeshiri** [comment]
yes sure, I just changed the title. thanks for your prime respond

**Comment by ltratt** [comment]
Thanks!

**Pull request merged**
