### PR TITLE
no_brainer

### PR DESCRIPTION
**Pull request by anar595**

### CODE REVIEW

**Comment by ltratt** [comment]
Have you contacted all the members? I believe that Xiaosen Wang is no longer taking this module for example.

**Comment by anar595** [comment]
Hi, 
Just got word from Sheng that he is changing module. 
Wang, Zhu and Stampelos haven't responded to me yet.

**Comment by ltratt** [comment]
OK, please let me know when they have responded.

**Comment by ltratt** [comment]
Who of this team has confirmed their membership?

**Comment by anar595** [comment]
Anar (me), Bayat, Valentin

**Comment by anar595** [comment]
Hi, 
Just got an email an hour ago that Stampelos is in.
That makes four of us: Stampelos, Anar, Bayat, Valentin.
Sheng is changing module. Wang and Zhu haven't responded to my emails.

**Comment by ltratt** [comment]
Ok, so please remove the members you *definitely* know aren't a part of the team (include Wang in that). In this case, I'm OK with it being a team of 4, should Zhu decide not to take the module.

**Comment by anar595** [comment]
ok, I removed Wang and Sheng

**Comment by ltratt** [comment]
OK. You need to restore the tab characters in the fields (you may need to re-copy and paste the lines). Once that's done, I think we can make the team official.

**Comment by anar595** [comment]
Done

**Comment by ltratt** [comment]
That hasn't worked. You need to copy and paste the lines without destroying tab characters.

**Comment by anar595** [comment]
Ok, I think it finally worked. 
Still no reply from Zhu

**Comment by ltratt** [comment]
OK, thanks.

**Pull request merged**
