### PR TITLE
New team registered, team name: Hermes 

### PR DESCRIPTION
**Pull request by MRJAB**

### CODE REVIEW

**Comment by ltratt** [comment]
Di Cheng is no longer a part of this team. Have you confirmed with all other members that they are active on the module?

**Comment by MRJAB** [comment]
Hi Lauren,


I have emailed all the other members after I received your email yesterday.

I have not received a response from Di Cheng but I got responses from two members:

1646278/1 Di, Cheng cheng.di@kcl.ac.uk Current Web Intelligence - is no longer part of the team as you have confirmed.

1620565/1 Lin, I-Hsuan i-hsuan.lin@kcl.ac.uk Current Robotics - he is not doing the module anymore.

1661609/1 Ranjan, Yatharth yatharth.ranjan@kcl.ac.uk Current Intelligent Systems - he is abroad and won't be back till next month but he said he is doing the module and wants to be part of the team.


Should I just update the members.txt file on GitHub?


Kind regards,


Khalil

________________________________

**Comment by ltratt** [comment]
Who's Lauren?

Yes, please update the members.txt and confirm here when you have heard from the other members.

**Comment by MRJAB** [comment]
Sorry, I meant Laurence - apologies.

I will update the members.txt now and will keep you updated - I still have to hear from one member:

1677449/1 Hashani, Gentrit gentrit.hashani@kcl.ac.uk Current Computing And Security


Regards,


Khalil

________________________________

**Pull request closed without merging**
