### PR TITLE
 Finalised team formation after consideration.

### PR DESCRIPTION
**Pull request by MRJAB**
members.txt updated!

### CODE REVIEW

**Comment by ltratt** [comment]
Thanks. Can you lower case the directory name? After that, we're good to go.

**Comment by MRJAB** [comment]
I can but I don't get it. Do you mean the entire link of the repository included in the repo.txt file or just to lower case Hermes.git to hermes.git and update the URL in repo.txt?

Many thanks,

On 20 Jan 2017, at 14:00, Laurence Tratt <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks. Can you lower case the directory name? After that, we're good to go.

**Comment by ltratt** [comment]
Something like `git mv Hermes hermes`, commit, then push.

**Comment by ltratt** [comment]
The directory name *inside* the repo needs to be lower-cased.

**Pull request closed without merging**
